#!/bin/bash

ejecutable=$1
entrada=$2
tiempo=$3

#Ejecutar archivo compilado
$ejecutable <<< $entrada &

CppPID=$!
./lib/scripts/matar $CppPID $tiempo &	#se manda llamar otro script con el PID del ejecutable y el tiempo limite

wait $CppPID
